[package]
name = "pkg-macros"
version = "3.0.0"
authors = ["James Whaley <juicy66173@gmail.com>"]
description = "Procedural macros for pkg."
license = "MIT or Apache-2.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"
